# deployment.yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "flowise"
  labels:
    app: "flowise"
spec:
  selector:
    matchLabels:
      app: "flowise"
  replicas: 1
  template:
    metadata:
      labels:
        app: "flowise"
    spec:
      containers:
      - name: "flowise"
        env:
        - name: DATABASE_PATH
          value: "/opt/flowise"
        - name: APIKEY_PATH
          value: "/opt/flowise"
        - name: SECRETKEY_PATH
          value: "/opt/flowise"
        - name: FLOWISE_SECRETKEY_OVERWRITE
          valueFrom:  
            secretKeyRef:  
              name: flowise-secrets
              key: flowise_secretkey_overwrite  
        - name: LOG_PATH
          value: "/opt/flowise/logs"
        - name: FLOWISE_USERNAME
          value: "admin"
        - name: FLOWISE_PASSWORD
          valueFrom:  
            secretKeyRef:  
              name: flowise-secrets
              key: flowise_password  
        image: "us-docker.pkg.dev/trending-threats/gcr.io/flowise:dev"
        imagePullPolicy: "Always"
        resources: 
          requests:
            cpu: 1
            memory: "1Gi"
        volumeMounts:
        - name: flowise-volume
          mountPath: /opt/flowise
      volumes:
      - name: flowise-volume
        persistentVolumeClaim:
          claimName: flowise-pvc 
