apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flowise-pvc
spec:
  accessModes:
    - ReadWriteMany  # Match PV's access mode
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwx  # Match PV's storage class
